Repository wecode-bootcamp-korea/fullstack2-1st-keudaran-studio-backend, pull requests merged in 2021-10, with the labels that each got.

#12 [이욱창] db 스키마 변경
  prisma/migrations/20211010073540_product_table_point_chnage/migration.sql
  prisma/schema.prisma
Labels: Status:수정요청

#13 [성지수] user Id Check 구현완료, err 미들웨어 구현 완료
  src/app.js
  src/controllers/userController.js
  src/errors/errorGenerator.js
  src/errors/index.js
  src/models/userDAO.js
  src/routes/userRouter.js
  src/services/userService.js
Labels: Status:리뷰 요청

#26 [이예봄, 김시원] 토큰인가 미들웨어 구현
  package-lock.json
  package.json
  src/app.js
  src/middleWares/index.js
  src/middleWares/tokenVerification.js
Labels: Status:리뷰 요청

#21 [이욱창] 상품 상세페이지 API 구현
  src/controllers/productController.js
  src/middleWares/errorHandler.js
  src/models/productDAO.js
  src/routes/productRouter.js
  src/services/index.js
  src/services/productService.js
Labels: Status:리뷰 요청

#29 [이예봄] 로그인 API + user check middleware 구현
  package-lock.json
  package.json
  src/app.js
  src/controllers/userController.js
  src/middleWares/index.js
  src/middleWares/tokenVerification.js
  src/models/userDAO.js
  src/routes/userRouter.js
  src/services/userService.js
  src/utils/errorGenerator.js
Labels: Status:리뷰 요청, status:기본 기능 구현 중

#16 [성지수] 칼럼에따라 적절한 예외처리 로직 구현 완료, 회원정보 수정 삭제 구현중
  src/controllers/userController.js
  src/middleWares/errorHandler.js
  src/models/userDAO.js
  src/routes/userRouter.js
  src/services/userService.js
  src/utils/formatCheckUser.js
Labels: Status:리뷰 요청

#32 [성지수] 회원가입시 토큰발행,user 정보 넘겨주기 완료, 회원정보 삭제 수정 구현중
  src/controllers/userController.js
  src/models/userDAO.js
  src/routes/userRouter.js
  src/services/userService.js
Labels: Status:리뷰 요청

#41 [신기철] fix : foreach -> map
  src/services/productService.js
Labels: Status:Accepted

#42 [이욱창] 리스트에 맞게 API 가공
  src/models/productDAO.js
  src/services/productService.js
Labels: Status:리뷰 요청
